region_pbf : [
  "https://download.geofabrik.de/europe/albania-latest.osm.pbf",
  "https://download.geofabrik.de/europe/andorra-latest.osm.pbf",
  "https://download.geofabrik.de/europe/austria-latest.osm.pbf",
  "https://download.geofabrik.de/europe/azores-latest.osm.pbf",
  # "https://download.geofabrik.de/europe/belarus-latest.osm.pbf",
  "https://download.geofabrik.de/europe/belgium-latest.osm.pbf",
  "https://download.geofabrik.de/europe/bosnia-herzegovina-latest.osm.pbf",
  "https://download.geofabrik.de/europe/bulgaria-latest.osm.pbf",
  "https://download.geofabrik.de/europe/croatia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/cyprus-latest.osm.pbf",
  "https://download.geofabrik.de/europe/czech-republic-latest.osm.pbf",
  "https://download.geofabrik.de/europe/denmark-latest.osm.pbf",
  "https://download.geofabrik.de/europe/estonia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/faroe-islands-latest.osm.pbf",
  "https://download.geofabrik.de/europe/finland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/france-latest.osm.pbf",
  # "https://download.geofabrik.de/europe/georgia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/germany-latest.osm.pbf",
  "https://download.geofabrik.de/europe/greece-latest.osm.pbf",
  "https://download.geofabrik.de/europe/guernsey-jersey-latest.osm.pbf",
  "https://download.geofabrik.de/europe/hungary-latest.osm.pbf",
  "https://download.geofabrik.de/europe/iceland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/ireland-and-northern-ireland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/isle-of-man-latest.osm.pbf",
  "https://download.geofabrik.de/europe/italy-latest.osm.pbf",
  "https://download.geofabrik.de/europe/kosovo-latest.osm.pbf",
  "https://download.geofabrik.de/europe/latvia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf",
  "https://download.geofabrik.de/europe/lithuania-latest.osm.pbf",  
  "https://download.geofabrik.de/europe/luxembourg-latest.osm.pbf",
  "https://download.geofabrik.de/europe/macedonia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/malta-latest.osm.pbf",
  # "https://download.geofabrik.de/europe/moldova-latest.osm.pbf",
  "https://download.geofabrik.de/europe/monaco-latest.osm.pbf",
  "https://download.geofabrik.de/europe/montenegro-latest.osm.pbf",
  "https://download.geofabrik.de/europe/netherlands-latest.osm.pbf",
  "https://download.geofabrik.de/europe/norway-latest.osm.pbf",
  "https://download.geofabrik.de/europe/poland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/portugal-latest.osm.pbf",
  "https://download.geofabrik.de/europe/romania-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/central-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/crimean-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/far-eastern-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/north-caucasus-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/northwestern-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/siberian-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/south-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/ural-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/volga-fed-district-latest.osm.pbf",
  "https://download.geofabrik.de/europe/serbia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/slovakia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/slovenia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/spain-latest.osm.pbf",
  "https://download.geofabrik.de/europe/sweden-latest.osm.pbf",
  "https://download.geofabrik.de/europe/switzerland-latest.osm.pbf",
  # "https://download.geofabrik.de/europe/turkey-latest.osm.pbf",
  # "https://download.geofabrik.de/europe/ukraine-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom-latest.osm.pbf"
]
collection:
  osm_tags:

  additional_columns: ["name", "operator", "addr:street","addr:housenumber", "addr:postcode", "addr:city", "addr:country", "phone", "email", "website", 
                       "capacity", "opening_hours", "wheelchair", "origin", "organic", "subway", "brand"]
  nodes : True
  ways : True
  relations : True
  
preparation:

subscription:
  repo_url: "https://github.com/goat-community/pois"
    