region_pbf : [
  "https://download.geofabrik.de/europe/united-kingdom/england/bedfordshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/berkshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/bristol-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/buckinghamshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/cambridgeshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/cheshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/cornwall-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/cumbria-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/derbyshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/devon-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/dorset-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/durham-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/east-sussex-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/east-yorkshire-with-hull-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/essex-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/gloucestershire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/greater-london-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/greater-manchester-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/hampshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/hertfordshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/isle-of-wight-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/lancashire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/leicestershire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/lincolnshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/kent-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/merseyside-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/norfolk-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/north-yorkshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/northamptonshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/northumberland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/nottinghamshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/oxfordshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/rutland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/shropshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/somerset-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/south-yorkshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/surrey-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/staffordshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/suffolk-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/tyne-and-wear-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/warwickshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/west-midlands-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/west-sussex-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/west-yorkshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/wiltshire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/england/worcestershire-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/scotland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom/wales-latest.osm.pbf" 
]
collection:
  osm_tags:
    amenity: ["atm", "bank", "bar", "biergarten", "bicycle_parking", "bicycle_rental", "bus_station", "cafe", "car_sharing", "charging_station",
              "cinema", "dentist", "doctors", "fast_food", "fuel", "ice_cream", "kneipp_water_cure", "library",
              "marketplace", "nightclub", "pharmacy", "place_of_worship", "planetarium", "post_box", "post_office", "parking", "pub",
              "recycling", "restaurant", "taxi", "theatre", "vending_machine"]
    shop: ["bakery", "butcher", "chemist", "clothes", "convenience", "deli", "farm", "fashion", "florist", "fuel", "general",
           "greengrocer", "grocery", "hairdresser", "health_food", "honey", "kiosk", "mall", "shoes", "sports",
           "supermarket", "wine"]
    tourism: ["alpine_hut", "apartment", "aquarium", "camp_site", "caravan_site", "chalet", "gallery", "guest_house",
               "hostel", "hotel", "motel", "museum", "theme_park", "zoo"]
    railway: ["platform", "station", "stop", "subway_entrance", "tram_stop"]
    leisure: ["amusement_arcade", "disc_golf_course", "dog_park", "escape_game", "fitness_centre", "fitness_station",
              "miniature_golf", "playground", "sports_centre", "sports_hall", "swimming_area", "water_park"]
    sport: ["fitness", "swimming", "yoga"]
    highway: ["bus_stop"]
    public_transport: ["station", "stop_position"]
    historic: ["aircraft", "aqueduct", "archaeological_site", "battlefield", "bomb_crater", "castle", "church",
               "city_gate", "citywalls", "fort", "locomotive", "memorial", "monastery", "monument",
               "railway_car", "ruins", "ship", "tank", "tomb", "tower", "vehicle", "wreck"]

  additional_columns: ["name", "operator", "addr:street","addr:housenumber", "addr:postcode", "addr:city", "addr:country", "phone", "email", "website", 
                       "capacity", "opening_hours", "wheelchair", "origin", "organic", "subway", "brand"]
  nodes : True
  ways : True
  relations : True
  
preparation:
  #TODO: add config?
  supermarket:
    classify_by_name:
      supermarket: 
        children:
          rewe     : ["rewe", "rewe city"]
        threshold: 0.7
        
subscription:
  repo_url: "https://github.com/goat-community/pois"
    

    