region_pbf : [
  "https://download.geofabrik.de/europe/belgium-latest.osm.pbf"
]
collection:
  osm_tags:
    amenity: ["atm", "bank", "bar", "biergarten", "bicycle_rental", "bus_station", "cafe", "car_sharing", "charging_station",
              "cinema", "dentist", "doctors", "fast_food", "fuel", "ice_cream", "kneipp_water_cure", "library",
              "marketplace", "nightclub", "pharmacy", "place_of_worship", "planetarium", "post_box", "post_office", "parking", "pub",
              "recycling", "restaurant", "taxi", "theatre", "vending_machine"]
    shop: ["bakery", "butcher", "chemist", "clothes", "convenience", "farm", "fashion", "florist", "fuel", "general",
           "greengrocer", "grocery", "hairdresser", "health_food", "honey", "kiosk", "mall", "shoes", "sports",
           "supermarket", "wine"]
    tourism: ["alpine_hut", "apartment", "aquarium", "camp_site", "caravan_site", "chalet", "gallery", "guest_house",
               "hostel", "hotel", "motel", "museum", "theme_park", "zoo"]
    railway: ["platform", "station", "stop", "subway_entrance", "tram_stop"]
    leisure: ["amusement_arcade", "disc_golf_course", "dog_park", "escape_game", "fitness_centre", "fitness_station",
              "miniature_golf", "playground", "sports_centre", "sports_hall", "swimming_area", "water_park"]
    sport: ["fitness", "swimming", "yoga"]
    highway: ["bus_stop"]
    public_transport: ["station", "stop_position"]
    historic: ["aircraft", "aqueduct", "archaeological_site", "battlefield", "bomb_crater", "castle", "church",
               "city_gate", "citywalls", "fort", "locomotive", "memorial", "monastery", "monument",
               "railway_car", "ruins", "ship", "tank", "tomb", "tower", "vehicle", "wreck"]

  additional_columns: ["name", "operator", "addr:street","addr:housenumber", "addr:postcode", "addr:city", "addr:country", "phone", "email", "website", 
                       "capacity", "opening_hours", "wheelchair", "origin", "organic", "subway", "brand"]
  nodes : True
  ways : True
  relations : True
  
preparation:
  supermarket:
    classify_by_name:
      supermarket: 
        children:
          delhaize: ["delhaize"]
          ad delhaize: ["ad delhaize"]
          proxy delhaize: ["proxy delhaize"]
          delhaize shop & go: ["delhaize shop & go"]
          carrefour: ["carrefour"]
          carrefour express: ["carrefour express"]
          carrefour market: ["carrefour market"]
          colruyt: ["colruyt"]
          okay: ["okay"]
          intermarché: ["intermarché"]
          match: ["match"]
          cora: ["cora"]
          makro: ["makro"]
          leader price: ["leader price"]
          spar: ["spar"]
          albert heijn     : ["albert heijn"]
          aldi  : ["aldi"]
          lidl  : ["lidl"]

        threshold: 0.9
      
      organic_supermarket:
        children:
          bio planet: ["bio planet"]
        threshold: 0.7
      
      chemist: 
        children:
          kruidvat : ["kruidvat"]
          etos : ["etos"]
          drogisterij: ["drogisterij"]
        threshold: 0.7
      
      # This should be international_supermarket, but it is merged with convenience
      convenience:
        children:
          # in dutch 
          turkse : ["turkse", "turks"]
          asia : ["asia", "asian", "aziatisch"]
          other : ["italiaanse", "polish", "spaans", "poolse"]
        threshold: 0.7

    classify_by_tag:
      # This should be international_supermarket, but it is merged with convenience
      international_supermarket:
        origin: [True] 
      organic_supermarket:
        organic: ["only"]
      chemist:
        name: ["di"]
    unmatched: "convenience"

  health_food: 
    classify_by_tag:
      organic_supermarket:
        shop: ["health_food"]

  chemist:
    classify_by_tag:
      chemist:
        shop: ["chemist"]

  convenience: 
    inherit: "supermarket"
  grocery: 
    inherit: "supermarket"
  deli: 
    inherit: "supermarket"
  
        
subscription:
  repo_url: "https://github.com/goat-community/pois"
    

    