region_pbf : [
    "https://download.geofabrik.de/europe/germany/saarland-latest.osm.pbf" , 
    "https://download.geofabrik.de/europe/germany/rheinland-pfalz-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.pbf", 
    "https://download.geofabrik.de/europe/germany/bayern-latest.osm.pbf", 
    "https://download.geofabrik.de/europe/germany/brandenburg-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/sachsen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/sachsen-anhalt-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/thueringen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/bremen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/hamburg-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/niedersachsen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/schleswig-holstein-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/nordrhein-westfalen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/hessen-latest.osm.pbf"
]
collection:
  osm_tags:
    amenity: ["atm", "bank", "bar", "biergarten", "bicycle_rental", "bus_station", "car_sharing", "charging_station",
              "cinema", "dentist", "doctors", "fast_food", "fuel", "ice_cream", "kneipp_water_cure", "library",
              "marketplace", "nightclub", "pharmacy", "place_of_worship", "planetarium", "post_box", "parking", "pub",
              "recycling", "restaurant", "taxi", "theatre"]
    shop: ["bakery", "butcher", "chemist", "clothes", "convenience", "fashion", "florist", "fuel", "general",
           "greengrocer", "grocery", "hairdresser", "health_food", "ice_cream", "kiosk", "mall", "shoes", "sports",
           "supermarket", "vine"]
    tourism: ["alpine_hut", "apartment", "aquarium", "camp_site", "caravan_site", "chalet", "gallery", "guest_house",
               "hostel", "hotel", "motel", "museum", "theme_park", "zoo"]
    railway: ["platform", "station", "stop", "subway_entrance", "tram_stop"]
    leisure: ["amusement_arcade", "disc_golf_course", "dog_park", "escape_game", "fitness_centre", "fitness_station",
              "miniature_golf", "playground", "sports_centre", "sports_hall", "swimming_area", "water_park"]
    sport: ["fitness", "swimming", "yoga"]
    highway: ["bus_stop"]
    public_transport: ["station", "stop_position"]
    historic: ["aircraft", "aqueduct", "archaeological_site", "battlefield", "bomb_crater", "castle", "church",
               "city_gate", "citywalls", "farm", "fort", "locomotive", "memorial", "monastery", "monument",
               "railway_car", "ruins", "ship", "tank", "tomb", "tower", "vehicle", "wreck"]

  additional_columns: ["name", "operator", "addr:street","addr:housenumber", "addr:postcode", "addr:city", "addr:country", "phone", "email", "website", 
                       "capacity", "opening_hours", "wheelchair", "origin", "organic", "subway", "brand"]
  nodes : True
  ways : True
  relations : True
  
preparation:
  supermarket:
    classify_by_name:
      supermarket: 
        children:
          rewe     : ["rewe", "rewe city"]
          tegut    : ["tegut"]
          feneberg : ["feneberg"]
          nahkauf  : ["nahkauf"]
          kupsch   : ["kupsch"]
          aez      : ["aez"]
          edeka    : ["edeka", "nah & gut", "e center", "diska", "e aktiv"]
          k+k      : ["k+k", "k&k"]
          nah&frisch : ["nah&frisch"]
          nah&gut  : ["nah&gut", "nah und gut"]
          cap-markt : ["cap-markt"]
          markant   : ["markant"]
          konsum    : ["konsum"]
          combi     : ["combi"]
          famila    : ["famila"]
          billa     : ["billa"]
        threshold: 0.7

      discount_supermarket: 
        children:
          aldi  : ["aldi"]
          lidl  : ["lidl"]
          netto : ["netto"]
          norma : ["norma"]
          penny : ["penny"]
        threshold: 0.8

      hypermarket: 
        children:
          real      : ["real"]
          v-markt   : ["v-markt"]
          kaufland  : ["kaufland"]
          hit       : ["hit"]
          globus    : ["globus"]
          marktkauf: ["marktkauf"]
        threshold: 0.9

      wholesale: 
        children:
          metro     : ["metro"]
          hamberger : ["hamberger"]
        threshold: 0.7
      
      organic_supermarket:
        children:
          denn's Biomarkt : ["denn's", "denns", "denn"]
          alnatura : ["alnatura"]
          vollcorner : ["vollcorner"]
          reformhaus : ["reformhaus"]
          naturkost : ["naturkost"]
          bio: ["bio", "bioladen"]
          vitalia : ["vitalia"]
        threshold: 0.7
      
      chemist: 
        children:
          rossmann : ["rossmann"]
          müller : ["müller", "mueller"]
          drogerie: ["drogerie"]
        threshold: 0.7
      
      variety_store: 
        children:
          tedi : ["tedi"]
        threshold: 0.7
      # This should be international_supermarket, but it is merged with convenience
      convenience:
        children:
          turkish : ["türkisch", "turkish", "turk"]
          asia : ["asia", "asien", "asiatische"]
          other : ["italienisch", "polnische", "spanische", "russisch"]
          mix markt : ["mix markt"]
        threshold: 0.7

    classify_by_tag:
      # This should be international_supermarket, but it is merged with convenience
      international_supermarket:
        origin: [True] 
      organic_supermarket:
        organic: ["only"]
      discount_supermarket: 
        name: ["np"]
      supermarket:
        name: ["combi"]
      chemist:
        name: ["dm"]
    unmatched: "convenience"

  health_food: 
    classify_by_tag:
      organic_supermarket:
        shop: ["health_food"]

  chemist:
    classify_by_tag:
      chemist:
        shop: ["chemist"]
  
  convenience: 
    inherit: "supermarket"
  grocery: 
    inherit: "supermarket"
  deli: 
    inherit: "supermarket"

subscription:
  repo_url: "https://github.com/goat-community/poi"
    