region_pbf : [
    "https://download.geofabrik.de/europe/germany/saarland-latest.osm.pbf" , 
    "https://download.geofabrik.de/europe/germany/rheinland-pfalz-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.pbf", 
    "https://download.geofabrik.de/europe/germany/bayern-latest.osm.pbf", 
    "https://download.geofabrik.de/europe/germany/brandenburg-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/sachsen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/sachsen-anhalt-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/thueringen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/bremen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/hamburg-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/niedersachsen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/schleswig-holstein-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/nordrhein-westfalen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/hessen-latest.osm.pbf"
]
collection:
  osm_tags:
    amenity : ["fuel", "taxi", "atm", "bank", "dentist", "doctors", "pharmacy", "post_box", "marketplace", "bar", "biergarten", "cafe", 
                "pub", "fast_food", "ice_cream", "restaurant", "theatre", "cinema", "library", "nightclub", "recycling", "car_sharing", "bicycle_rental", 
                "charging_station", "bus_station", "playground"]
    shop    : ["clothes", "convenience", "general", "fashion", "fuel", "bakery", "butcher", "florist", "grocery", "greengrocer", "kiosk", "mall", "shoes", "sports", 
                "supermarket", "hairdresser", "health_food", "chemist", "ice_cream"]
    tourism : ["hotel", "museum", "hostel", "guest_house"]
    railway : ["station", "platform", "stop", "tram_stop", "subway_entrance"]
    leisure : ["playground", "fitness_station", "water_park", "sports_centre", 'sports_hall', "fitness_centre"]
    sport   : ["yoga", "fitness"]
    highway : ["bus_stop"]
    public_transport : ["stop_position", "station"]

  additional_columns: ["name", "brand", "addr:street","addr:housenumber", "addr:postcode", "addr:city", "addr:country", "phone", "website", 
                        "opening_hours", "operator", "origin", "organic", "subway"]
  nodes : True
  ways : True
  relations : True
  
preparation:
  supermarket:
    classify_by_name:
      supermarket: 
        children:
          rewe     : ["rewe", "rewe city"]
          tegut    : ["tegut"]
          feneberg : ["feneberg"]
          nahkauf  : ["nahkauf"]
          kupsch   : ["kupsch"]
          aez      : ["aez"]
          edeka    : ["edeka", "nah & gut", "e center", "diska", "e aktiv"]
          k+k      : ["k+k", "k&k"]
          nah&frisch : ["nah&frisch"]
          nah&gut  : ["nah&gut", "nah und gut"]
          cap-markt : ["cap-markt"]
          markant   : ["markant"]
          konsum    : ["konsum"]
          combi     : ["combi"]
          famila    : ["famila"]
          billa     : ["billa"]
        threshold: 0.7

      discount_supermarket: 
        children:
          aldi  : ["aldi"]
          lidl  : ["lidl"]
          netto : ["netto"]
          norma : ["norma"]
          penny : ["penny"]
        threshold: 0.8

      hypermarket: 
        children:
          real      : ["real"]
          v-markt   : ["v-markt"]
          kaufland  : ["kaufland"]
          hit       : ["hit"]
          globus    : ["globus"]
          marktkauf: ["marktkauf"]
        threshold: 0.9

      wholesale: 
        children:
          metro     : ["metro"]
          hamberger : ["hamberger"]
        threshold: 0.7
      
      organic_supermarket:
        children:
          denn's Biomarkt : ["denn's", "denns", "denn"]
          alnatura : ["alnatura"]
          vollcorner : ["vollcorner"]
          reformhaus : ["reformhaus"]
          naturkost : ["naturkost"]
          bio: ["bio", "bioladen"]
          vitalia : ["vitalia"]
        threshold: 0.7
      
      chemist: 
        children:
          rossmann : ["rossmann"]
          müller : ["müller", "mueller"]
          drogerie: ["drogerie"]
        threshold: 0.7
      
      variety_store: 
        children:
          tedi : ["tedi"]
        threshold: 0.7
      # This should be international_supermarket, but it is merged with convenience
      convenience:
        children:
          turkish : ["türkisch", "turkish", "turk"]
          asia : ["asia", "asien", "asiatische"]
          other : ["italienisch", "polnische", "spanische", "russisch"]
          mix markt : ["mix markt"]
        threshold: 0.7

    classify_by_tag:
      # This should be international_supermarket, but it is merged with convenience
      international_supermarket:
        origin: [True] 
      organic_supermarket:
        organic: ["only"]
      discount_supermarket: 
        name: ["np"]
      supermarket:
        name: ["combi"]
      chemist:
        name: ["dm"]
    unmatched: "convenience"

  health_food: 
    classify_by_tag:
      organic_supermarket:
        shop: ["health_food"]

  chemist:
    classify_by_tag:
      chemist:
        shop: ["chemist"]

  convenience: 
    inherit: "supermarket"
  grocery: 
    inherit: "supermarket"
  deli: 
    inherit: "supermarket"
  
subscription:
  repo_url: "https://github.com/goat-community/poi"
    
  # discount_gym: 
  #   fitx           : ["fitx"]
  #   mcfit          : ["mcfit"]
  #   fitstar        : ["fitstar","fit-star", "fit star"]
  #   cleverfit      : ["cleverfit" ,"clever fit"]
  #   jumpersfitness : ["jumpersfitness" ,"jumpers fitness"]

  # community_sport_centre: ["bezirkssportanlage"]

  # # Not used (operators for various cities in Germany are too different)
  # operators_bicycle_rental: ["münchner verkehrs gesellschaft", "münchner verkehrsgesellschaft", "mvg"]

  # sport:
  #   sport_var_disc   : ["table_tennis"]
  #   leisure_var_add  : ["sports_hall", "fitness_center", "sport_center", "track", "pitch"]
  #   leisure_var_disc : ["fitness_station"]
    